"""Base callback interfaces used by orchestration agents and LLM runtimes."""

from typing import Any


class AgentCallbacks:
    """Base callback interface for agents and LLMs."""

    async def on_agent_start(
        self,
        agent_name,
        payload_input: Any | None = None,
        messages: list[Any] | None = None,
        run_id: str | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> dict:
        """
        Callback method that runs when an agent starts processing.

        This method is called at the beginning of an agent's execution, providing information
        about the agent session and its context.

        Parameters:
            self: The instance of the callback handler class.
            agent_name: Name of the agent that is starting.
            payload_input: Dictionary containing the agent's input.
            messages: List of message dictionaries representing the conversation history.
            run_id: Unique identifier for this specific agent run.
            tags: Optional list of string tags associated with this agent run.
            metadata: Optional dictionary containing additional metadata about the run.
            **kwargs: Additional keyword arguments that might be passed to the callback.

        Returns:
            dict: The agent tracking information, this is made available to all other
                callbacks using the agent_tracking_info key in kwargs.
        """
        return {}

    async def on_agent_end(
        self,
        agent_name,
        response: Any | None = None,
        messages: list[Any] | None = None,
        run_id: str | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> Any:
        """
        Callback method that runs when an agent completes its processing.

        This method is called at the end of an agent's execution, providing information
        about the completed agent session and its response.

        Parameters:
            self: The instance of the callback handler class.
            agent_name: Name of the agent that is completing.
            response: Dictionary containing the agent's response or output.
            run_id: Unique identifier for this specific agent run.
            tags: Optional list of string tags associated with this agent run.
            metadata: Optional dictionary containing additional metadata about the run.
            **kwargs: Additional keyword arguments that might be passed to the callback.

        Returns:
            Any: The return value is implementation-dependent.
        """
        pass

    async def on_llm_start(
        self,
        name: str,
        payload_input: Any,
        run_id: str | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> Any:
        """
        Callback method that runs when an llm starts processing.

        This method is called at the beginning of an llm's execution, providing information
        about the llm session and its context.

        Parameters:
            self: The instance of the callback handler class.
            agent_name: Name of the agent that is starting.
            payload_input: Dictionary containing the agent's input.
            messages: List of message dictionaries representing the conversation history.
            run_id: Unique identifier for this specific agent run.
            tags: Optional list of string tags associated with this agent run.
            metadata: Optional dictionary containing additional metadata about the run.
            **kwargs: Additional keyword arguments that might be passed to the callback.

        Returns:
            Any: The return value is implementation-dependent.
        """
        pass

    async def on_llm_new_token(
        self,
        token: str | None = None,
        name: str | None = None,
        payload_input: Any | None = None,
        run_id: str | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Called when a new token is generated by the LLM.

        Args:
            self: The instance of the callback handler class.
            token: The new token generated (text)
            name: Name of the LLM that is streaming tokens.
            payload_input: Optional input payload for the LLM run.
            run_id: Unique identifier for this specific LLM run.
            tags: Optional list of string tags associated with this LLM run.
            metadata: Optional dictionary containing additional metadata about the run.
            **kwargs: Additional keyword arguments that might be passed to the callback.
        """
        pass

    async def on_llm_end(
        self,
        name: str,
        output: Any | None = None,
        run_id: str | None = None,
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> Any:
        """
        Callback method that runs when an llm stops.

        This method is called at the end of an llm's execution, providing information
        about the llm session and its context.

        Parameters:
            self: The instance of the callback handler class.
            name: Name of the LLM that is starting.
            output: Dictionary containing the agent's input.
            run_id: Unique identifier for this specific agent run.
            tags: Optional list of string tags associated with this agent run.
            metadata: Optional dictionary containing additional metadata about the run.
            **kwargs: Additional keyword arguments that might be passed to the callback.

        Returns:
            Any: The return value is implementation-dependent.
        """

    pass
